Comment.destroy_all
Post.destroy_all
UserTag.destroy_all
Tag.destroy_all
User.destroy_all

# dc = Section.create(name: "DC")
# issues = Section.create(name: "Issues")
# elections = Section.create(name: "Elections")
# government = Section.create(name: "Government")
Post.create(title: "Welcome to DCFuture", summary: "Why This Blog Exists", body: "Washington, DC is a city full of concurrent, and often conflicting, extremes. Extreme wealth and extreme poverty. Disenfranchisement and tremendous power. Growth and displacement. Trendiness and tradition. But regardless of where in the city we live, every one of the more than half a million of us who live here has another word for the District: home. Whether our intended stay in the nation’s capital is temporary or permanent, all of us living in DC have a stake in the well-being of the unique city we call home. Yet all too often, the policy-making process fails to adequate reflect the sum of our values, as the voices of everyday DC residents tend to be drowned out by well-heeled professional lobbyists and the business interests they represent. It’s not as if we suffer from a shortage of valuable voices. This is one of the most educated and politically savvy cities out there – so many of our nation’s policy experts, advocacy specialists and leading political thinkers reside within our borders. If there’s an issue, somebody in DC wants to address it, somebody has an innovative and socially-beneficial solution in hand, and somebody knows how to build a campaign to enact that solution into law. We have the capacity here to do so much more, to transform our government from business as usual to one that leads by example. But we need to ensure those solutions are being lifted up, by citizens from Columbia Heights to Congress Heights, and echoing throughout the rarefied marble halls of power in the John A. Wilson Building, a deafening roar that makes it easy for our elected officials to do the right thing. DCFuture.com is the virtual town square where DC residents can learn about our unique city, think big about its future, plug into the hot and emerging issue and political campaigns of the moment, and even start their own campaigns.", user: admin, section: "dc")
Post.create(title: "test test", summary: "I like pie", body: "More test", section: "issues")
Tag.create(tag: "housing")
Tag.create(tag: "ethics")
Tag.create(tag: "pay-to-play")
Tag.create(tag: "homelessness")
Tag.create(tag: "economic development")
Tag.create(tag: "gentrification")
Tag.create(tag: "open gov")
Tag.create(tag: "fair elections")
Tag.create(tag: "minimum wage")
Tag.create(tag: "labor")
Tag.create(tag: "family leave")
Tag.create(tag: "child care")
Tag.create(tag: "jobs")
Tag.create(tag: "safety net")
Tag.create(tag: "health care")
Tag.create(tag: "budget")
Tag.create(tag: "taxes")
Tag.create(tag: "police")
Tag.create(tag: "LGBTQ")
Tag.create(tag: "reproductive rights")
Tag.create(tag: "education")
Tag.create(tag: "Congress")
Tag.create(tag: "President Obama")
Tag.create(tag: "Obama Administration")
Tag.create(tag: "DC statehood")
Tag.create(tag: "transportation")
Tag.create(tag: "energy")
Tag.create(tag: "utilities")
Tag.create(tag: "environment")
Tag.create(tag: "parks")
Tag.create(tag: "land use")
Tag.create(tag: "BlackLivesMatter")
Tag.create(tag: "Congress")
Tag.create(tag: "Ward 1")
Tag.create(tag: "Ward 2")
Tag.create(tag: "Ward 3")
Tag.create(tag: "Ward 4")
Tag.create(tag: "Ward 5")
Tag.create(tag: "Ward 6")
Tag.create(tag: "Ward 7")
Tag.create(tag: "Ward 8")
Tag.create(tag: "Muriel Bowser")
Tag.create(tag: "Bowser Administration")
Tag.create(tag: "DC Council")
Tag.create(tag: "Phil Mendelson")
Tag.create(tag: "Anita Bonds")
Tag.create(tag: "Vincent Orange")
Tag.create(tag: "Elissa Silverman")
Tag.create(tag: "David Grosso")
Tag.create(tag: "Brianne Nadeau")
Tag.create(tag: "Jack Evans")
Tag.create(tag: "Mary Cheh")
Tag.create(tag: "Brandon Todd")
Tag.create(tag: "Kenyon McDuffie")
Tag.create(tag: "Charles Allen")
Tag.create(tag: "Yvette Alexander")
Tag.create(tag: "LaRuby May")
Tag.create(tag: "Karl Racine")
